### PR TITLE
Fix interrupt support, add mode 0 support

### PR DESCRIPTION
**Pull request by pixelherodev**
This fixes support for interrupt mode 2 and adds support for mode 0.

### CODE REVIEW

**Comment by jsanchezv** [comment]
Hi pixelherodev,

Thanks by the patch, but I'm not very happy with the call to decodeOpcode from interrupt. I need to think about it.

**Comment by pixelherodev** [comment]
Alright - I'm more than willing to use the fork in my project

Let me know if you come up with a better solution.

Also, what's three problem with it? The idea was taken directly from the official manual. Pretty sure that's what it is supposed to do.

**Comment by jsanchezv** [comment]
I'm reading the official doc from Zilog and this document: [Z80 Interrupts](http://www.z80.info/zip/z80-interrupts.pdf).

First, in IM0 mode, the PC register isn't stacked automatically as interrupt() does now. Then, when a CALL opcode is inserted by the peripherial, the target address will be readed as a normal memory read, but the data can't be readed from memory and the PC isn't incremented. decodeOpcode does the wrong thing, IMHO.

Surprisingly, appears that IM1 executes a RST 38 opcode, as when the CPU reads 0xFF from bus, so the PC register is stacked by RST instruction, not by the own interrupt.

It's an interesting question your patch... :)

**Comment by pixelherodev** [comment]
Huh, interesting indeed. I think that as long as PC isn't automatically pushed in mode 0 the rest of it is accurate.

**Comment by pixelherodev** [comment]
Actually, just understood what you were saying about CALL. With the exception of multi-byte instructions it's accurate though I think...

**Comment by pixelherodev** [comment]
Could have multi-byte instructions read extra bytes from further calls to `interrupt_value`?

**Comment by pixelherodev** [comment]
My current method is to use a std::vector to hold the instruction and pop the back of it to get the value. For my case at least, it would be as easy as modifying it to first push the remaining bytes, but I can see how it would be different for different use cases and the goal isn't to make it worth with just one project :thinking:

**Comment by jsanchezv** [comment]
No, multi-byte instructions are readed as memory, so can't be readed using another method. Really, any instruction code can be sended to CPU, including prefixed instructions with CB, DD/FD, ED, etc.

We need a generic solution, not a one case solution.

I'm using the core in this emulator [ZXBaremulator](http://zxmini.speccy.org), so I don't have access to standard C++ libraries as std::vector.

I have thought a general solution, but that impacts on fetch, peek8 and poke8 handlers.

I have curiosity to know what's the platform you are emulating to know a real case to IM0 interrupts. :)

**Comment by pixelherodev** [comment]
Sorry for the delay, I ~~forgot~~ was busy.

Potential solution:

```cpp
class z80_peripheral {
public:
    virtual bool isInterrupting() = 0;
    virtual uint8_t acknowledgeInterrupt() = 0;
};
```

and modify the z80 class to have a `registerPeripheral(z80_peripheral *);` and `unregisterPeripheral(z80_peripheral *);` Is using malloc/realloc for a quasi-dynamic array an option?

**Comment by pixelherodev** [comment]
The beauty of this solution is that implementation is trivial both for library-side and client-side.

A client device could be e.g. keyboard. Upon acknowledgement, sets internal state to `false`. Using malloc/realloc, just allocate space for the pointers (e.g. registerPeripheral could be `peripherals = realloc(peripherals, (++peripheral_count) * sizeof(z80_peripheral*));peripherals[peripheral_count - 1] = peripheral;`

**Comment by pixelherodev** [comment]
Idea: what if my above proposed peripheral class is extended to support a daisy chain the way an actual Z80 would see it? Then it's just a matter of using (z80_peripheral*)->acknowledge_interrupt() which propagates throughout the chain.

**Comment by jsanchezv** [comment]
The real problem is to find a more general solution. Is needed to handle multibyte instructions, including degenerated ones (as a undefined-long DD/FD sequence) processing the instruction with decodeOpcode and without modify the PC register, reading the data bytes (as the target address in a CALL instruction) using the same memory reads as usual.

A possible solution can be create a new class based on z80operations to handle read/write memory operations on interrupts and when an interrupt is triggered in IM0 mode:

1.- Save regPC
2.- Assign the new class to handle memory ops.
3.- decodeOpcode call.
4.- Restore regPC
5.- Reassign the old z80operations handler.

Doing this, I can see another design problem: the Z80operations class is big and, probably, should be refactorized  to classify operations in:

1.- Memory operations
2.- in/out port operations
3.- Interrupt operations
4.- Misc. operations (execDone & breakpoint basically).

Another problem is to add a complete test for all these changes. I don't know any computer that uses IM0 and, on the ZX Spectrum, the IM0 is equal than a IM1 (executes an 0xFF opcode, RST 38h).

**Comment by pixelherodev** [comment]
From my understanding, interrupting peripherals would essentially "replace" the RAM for multi-byte instructions, correct?

They would intercept the next reads and give the correct values?

**Comment by pixelherodev** [comment]
I think I've figured this out.

I finally took the time to properly read up on how the z80 interrupt chain works, and I've got a solution that I hope works for you as well.

A z80peripheral class with a constructor that takes a pointer to a z80peripheral along with the CPU. The z80 class is extended to contain a z80peripheral pointer. The class also contains two boolean values, IEO and IEI (Interrupt Enable Output and Interrupt Enable Input).

The z80peripheral class is completely non-virtualized, so its methods *cannot* be overridden (except for a single method that's called when its interrupt is acknowledged).

The z80 class is modified so that instead of calling z80operations->isActiveINT it calls `z80peripheral->isActiveINT` on the z80 peripheral closest to the CPU function, which returns true if IEI is low.

Aside from the constructors, there are four defined functions. First is `setIEO`, which sets IEO (and calls setIEI on the next device if it's not the closest). To interrupt, a device just calls `setIEO(low)`, thus propagating the low signal to the device closest to the z80, which means that isActiveINT returns true. Second is setIEI, which is called by the prior device. The third function is `acknowledgeInterrupt`. When the z80 acknowledges an interrupt, it calls this function on the closest peripheral. The peripheral will check if its IEI is high, and if so, will call the fourth function, a virtual function called interruptAcknowledged`, otherwise, it propagates it to the next device.

The device furthest from the CPU has its IEI high always.

Replacing the interrupt_value thing, the z80 class would be extended to have a `putData` function that stores a value in a dedicated variable, which is used instead of calling interrupt_value.

Thoughts?

I'm working on implementing this now, will let you know how it goes

**Comment by pixelherodev** [comment]
How does this class look?

```cpp
#pragma once

class Z80;
class Z80peripheral {
public:
	friend class Z80;
	Z80peripheral(Z80 *cpu, Z80peripheral *next_device);
	virtual ~Z80peripheral();
	bool isActiveINT();
	uint8_t getData();
protected:
	void interrupt(uint8_t data = 0);
private:
	void acknowledgeInterrupt();
	void propagate();
	Z80peripheral *next_device, *previous_device;
	Z80 *cpu;
	bool *IEI, *IEO;
	bool interrupting;
	uint8_t data;
};
```
The only API it exposes publicly is to check if it's interrupting, and what it'll put on the CPU's data bus when it's acknowledged, which can be useful for debugging but are completely harmless.
The interrupt method is not virtual, but should be callable from any subclasses, and only the CPU can call acknowledgeInterrupt.

I've deliberately made sure that z80cpp will continue to work with all existing code as long as no peripheral is constructed, so this does NOT break compatibility AT ALL.

I still need to test it, but how does it look?

**Comment by pixelherodev** [comment]
Wait no, this still doesn't solve "reading the data bytes (as the target address in a CALL instruction) using the same memory reads as usual."

**Pull request closed without merging**
